/* Phase 1 quiz bank — topic t1 · Latency, throughput & percentiles.
   20 questions grounded in lessons/0001-performance-vocabulary.html.
   Questions 1-5 are reused verbatim from diagnostics/phase1-questions.js. */

var PHASE1_BANK_T1 = [
  // ---- Reused from phase1-questions.js (verbatim) ----
  { topic: 't1', q: "Your service reports p50 = 40 ms and p99 = 900 ms. What does the p99 figure mean?",
    options: ["The single slowest request took nine hundred milliseconds",
              "One percent of requests exceed nine hundred milliseconds",
              "Ninety-nine percent of requests exceed nine hundred milliseconds"],
    answer: 1, explain: "p99 is the threshold 99% of requests beat; the remaining 1% are slower. It says nothing about the single worst request." },
  { topic: 't1', q: "Which change raises throughput but can also raise latency?",
    options: ["Processing requests in larger batches per iteration",
              "Caching frequent responses closer to the client",
              "Removing synchronous blocking calls from the path"],
    answer: 0, explain: "Batching amortizes overhead (throughput up) but early arrivals wait for the batch to fill (latency up)." },
  { topic: 't1', q: "A page fans out to 50 backend calls, each with independent p99 = 1 s. What fraction of pages hit at least one slow call?",
    options: ["Roughly one percent of all the pages",
              "Roughly five percent of all the pages",
              "Roughly forty percent of all the pages"],
    answer: 2, explain: "1 − 0.99^50 ≈ 39.5%. Fan-out amplifies the tail: a rare event per call becomes common per page." },
  { topic: 't1', q: "Why do tail-latency problems often hit your most valuable users hardest?",
    options: ["Valuable users send many more malformed requests",
              "Their heavy accounts process the most data",
              "They use older clients with slower connections"],
    answer: 1, explain: "The slowest requests correlate with the largest accounts — most data, most purchases. DDIA cites Amazon targeting p999 for exactly this reason." },
  { topic: 't1', q: "Roughly how much slower is a same-datacenter round trip than a main-memory reference?",
    options: ["Around five thousand times slower than memory",
              "Around fifty times slower than memory access",
              "Around five times slower than memory access"],
    answer: 0, explain: "≈500 µs vs ≈100 ns = 5,000×. This cliff is why an in-memory cache beats an extra network hop almost always." },

  // ---- New questions ----
  { topic: 't1', q: 'Which statement correctly describes throughput as a performance metric?',
    options: ['The time one single request takes to finish',
              'The fraction of requests that finish without errors',
              'The number of requests completed every single second'],
    answer: 2, explain: 'Throughput counts completed requests per second (RPS/QPS, or tokens/second for LLMs); latency is the per-request time seen by the caller.' },
  { topic: 't1', q: 'In this lesson\'s vocabulary, what is an SLO?',
    options: ['A log of every slow request the system served',
              'A numeric target like p99 latency below 500 ms',
              'A tool that measures percentiles across all production requests'],
    answer: 1, explain: 'An SLO (Service Level Objective) states a measurable target such as "p99 latency < 500 ms at 10k RPS" - designs are judged against SLOs, not vibes.' },
  { topic: 't1', q: 'What does the p50 latency of a service represent?',
    options: ['The median request time, the typical user experience',
              'The average request time across all sampled requests',
              'The slowest request seen in the measurement window'],
    answer: 0, explain: 'p50 is the median: half of requests are faster and half slower, which makes it the best single proxy for the typical experience.' },
  { topic: 't1', q: 'An interviewer says: design a token-generation service handling 100,000 requests per second. What should you ask first?',
    options: ['Which programming language the service is using',
              'How many engineers will maintain the service',
              'What latency SLO the service must meet'],
    answer: 2, explain: 'The prompt already fixes a throughput target; the missing axis is latency, so your first move is to ask for the latency SLO.' },
  { topic: 't1', q: 'Why is LLM decode memory-bandwidth-bound rather than compute-bound?',
    options: ['The GPU compute units are too slow for matmuls',
              'Each new token requires reading essentially all model weights',
              'The network link into the GPU throttles token output'],
    answer: 1, explain: 'Generating one token streams essentially all weights from GPU memory, so bandwidth sets the floor while the compute units sit mostly idle.' },
  { topic: 't1', q: 'A dashboard shows only mean latency, which looks healthy at 80 ms. What problem can stay hidden?',
    options: ['A slow tail hurting a few real users',
              'A steady clock drift across the server fleet',
              'A shortage of samples inside the measurement window'],
    answer: 0, explain: 'Thousands of fast requests dominate a mean, so multi-second outliers barely move it - report latency as a distribution with percentiles.' },
  { topic: 't1', q: 'You cut a page\'s fan-out from 100 backend calls to 10, each call keeping independent p99 = 1 s. What happens to the share of slow pages?',
    options: ['It stays the same since p99 is unchanged',
              'It drops from roughly sixty-three to ten percent',
              'It rises because each call now carries more'],
    answer: 1, explain: '1 - 0.99^100 is about 63% while 1 - 0.99^10 is about 10%, so reducing fan-out directly shrinks tail latency amplification.' },
  { topic: 't1', q: 'A 140 GB model runs on a GPU with 3.35 TB/s memory bandwidth. What is the single-request decode floor?',
    options: ['About 240 tokens per second generated',
              'About 2.4 tokens per second generated',
              'About 24 tokens per second generated'],
    answer: 2, explain: '140 GB / 3.35 TB/s is about 42 ms per token, which caps one user at roughly 24 tokens/second while compute sits mostly idle.' },
  { topic: 't1', q: 'You can serve a hot value from local memory or fetch it from another service in the same datacenter. Why does memory win so decisively?',
    options: ['The round trip costs roughly five thousand memory references',
              'The remote service must deserialize the value before replying',
              'The datacenter network drops packets under any sustained load'],
    answer: 0, explain: 'A datacenter round trip is about 500 us versus about 100 ns for memory - a 5,000x cliff, so touch the slow tiers as rarely as possible.' },
  { topic: 't1', q: 'A workflow needs sequential round trips across an ocean at 150 ms each. Roughly how many fit in one second?',
    options: ['About two thousand round trips',
              'About sixty or seventy trips',
              'About six or seven trips'],
    answer: 2, explain: '1 s / 150 ms allows only 6-7 sequential ocean round trips, versus roughly 2,000 inside a datacenter - distance dominates the budget.' },
  { topic: 't1', q: 'In chat-style LLM serving, which metric captures the typing speed after the response has started?',
    options: ['Time to first token, TTFT',
              'Time per output token, TPOT',
              'Total requests served per second'],
    answer: 1, explain: 'TPOT measures the interval between output tokens once generation starts; TTFT covers the wait before the first token appears.' },
  { topic: 't1', q: 'Serving systems batch many users\' decode steps onto one pass over the model weights. What does this achieve?',
    options: ['One expensive weight read is amortized across many users',
              'Each user receives a private copy of the weights',
              'The GPU can skip reading weights for short prompts'],
    answer: 0, explain: 'Decode is memory-bandwidth-bound, so sharing one weight read across a batch raises throughput - the classic batching trade again.' },
  { topic: 't1', q: 'Using the lesson\'s anchor numbers, what is the latency gap between a random 4 KB SSD read and an HDD seek?',
    options: ['The HDD is about seven times slower',
              'They are roughly equal for random reads',
              'The HDD is nearly seventy times slower'],
    answer: 2, explain: '10 ms versus 150 us is roughly a 65-70x gap, which is why random-read-heavy workloads avoid spinning disks.' },
  { topic: 't1', q: 'What did Amazon famously observe about added latency?',
    options: ['Every extra second doubled the checkout abandonment rate',
              'Roughly one percent sales loss per 100 ms',
              'Latency only mattered for users on mobile networks'],
    answer: 1, explain: 'DDIA ch. 1 cites Amazon observing about 1% sales loss per added 100 ms - the business case for specifying SLOs at p999.' },
  { topic: 't1', q: 'According to the lesson, which improvement helps both latency and throughput at once?',
    options: ['Caching common responses close to the user',
              'Batching more requests into every processing iteration',
              'Adding an extra network hop for validation'],
    answer: 0, explain: 'Caching removes work from the request path, cutting latency and freeing capacity, while batching trades latency for throughput.' },
];
