// Quiz bank — t2 · Back-of-envelope estimation (Lesson 0002)
// 20 questions: 5 reused from phase1-questions.js + 15 new.
// Invariants: 3 options per question with equal word counts; answer
// indices distributed 7/7/6 across 0/1/2, never 3 identical in a row.
var PHASE1_BANK_T2 = [
  // ---- reused verbatim from phase1-questions.js ----
  { topic: 't2', q: "A product has 5M DAU, each making 20 requests/day. Approximate average QPS?",
    options: ["About ten thousand requests every single second",
              "About one hundred requests every single second",
              "About one thousand requests every single second"],
    answer: 2, explain: "5M × 20 = 10^8 requests/day ÷ 10^5 s/day = 1,000 QPS. Round 86,400 to 10^5 — always." },
  { topic: 't2', q: "Users upload 2 TB of photos per day. With 3× replication, storage needed per year?",
    options: ["Roughly two petabytes of raw yearly storage",
              "Roughly twenty petabytes of raw yearly storage",
              "Roughly two hundred terabytes of yearly storage"],
    answer: 0, explain: "2 TB × 365 ≈ 730 TB × 3 replicas ≈ 2.2 PB. Forgetting the replication factor is the classic estimation trap." },
  { topic: 't2', q: "Why quote '~15k QPS' instead of '13,889 QPS' in an interview?",
    options: ["Interviewers penalize any use of exact numbers",
              "Extra precision is noise beyond assumption quality",
              "Round numbers are always easier to multiply"],
    answer: 1, explain: "Your inputs are guesses within 2×; a third significant digit is false precision — it signals you don't know what the numbers are for." },
  { topic: 't2', q: "A 70B-parameter model in bf16 needs roughly how much memory for weights alone?",
    options: ["About one hundred forty gigabytes of memory",
              "About seventy gigabytes of memory in total",
              "About two hundred eighty gigabytes of memory"],
    answer: 0, explain: "bf16 = 2 bytes/param → 70B × 2 B = 140 GB. Params × bytes-per-param is the whole trick." },
  { topic: 't2', q: "What does a peak factor of 5× mean for capacity planning?",
    options: ["Provision five times the yearly storage estimate",
              "Expect five times more reads than writes",
              "Provision for five times the average QPS"],
    answer: 2, explain: "Traffic is bursty; you build for peak, not average. Peak factor multiplies QPS, not storage or read ratio." },

  // ---- new questions ----
  { topic: 't2', q: "Roughly how many average RPS does 1 million requests per day work out to?",
    options: ["About one hundred twenty requests per second",
              "About twelve requests arriving every single second",
              "About one point two requests per second"],
    answer: 1, explain: "10^6 requests/day / 10^5 s/day ~ 12 RPS -- the instant sanity anchor from the rules-of-thumb table." },
  { topic: 't2', q: "A service has 20M DAU, each making 5 requests/day, with a 5x peak factor. Peak QPS to provision?",
    options: ["Roughly five thousand requests per second peak",
              "Roughly five hundred requests per second peak",
              "Roughly fifty thousand requests per second peak"],
    answer: 0, explain: "20M x 5 = 10^8 requests/day / 10^5 s = 1,000 avg QPS x 5 peak = 5,000 peak QPS." },
  { topic: 't2', q: "A service writes 10^7 items/day at 1 KB each. Provisioned storage per year with 3x replication?",
    options: ["On the order of one terabyte provisioned",
              "On the order of one petabyte provisioned",
              "On the order of ten terabytes provisioned"],
    answer: 2, explain: "10^7 x 1 KB = 10 GB/day x 365 ~ 3.65 TB raw x 3 replicas ~ 11 TB provisioned." },
  { topic: 't2', q: "A photo service ingests 10 TB of uploads per day. Sustained ingest bandwidth?",
    options: ["About ten megabytes every second sustained",
              "About one hundred megabytes per second",
              "About ten gigabytes every second sustained"],
    answer: 1, explain: "10 TB/day = 10^13 B / 10^5 s/day ~ 100 MB/s sustained ingest -- egress at 100:1 reads would be ~10 GB/s." },
  { topic: 't2', q: "Your estimate shows a 100:1 read:write ratio on a social feed. Which design door opens?",
    options: ["Cache tier plus precomputed timelines for reads",
              "Shard the write path across many nodes",
              "Move all posts into object storage immediately"],
    answer: 0, explain: "Read:write >= 10:1 means read-dominated: cache tier, replicas, and fan-out-on-write precomputed feeds -- 200 writes/s stays boring." },
  { topic: 't2', q: "A 70B-parameter model quantized to int8 needs roughly how much memory for weights?",
    options: ["About one hundred forty gigabytes of weights",
              "About seventy gigabytes of memory for weights",
              "About thirty five gigabytes of weight memory"],
    answer: 1, explain: "int8 = 1 byte/param -> 70B x 1 B = 70 GB, exactly half the bf16 figure of 140 GB." },
  { topic: 't2', q: "A model has 80 layers, 8 KV heads, head_dim 128. KV cache per token at bf16 (2 bytes)?",
    options: ["About three kilobytes per token stored",
              "About thirty megabytes per token stored",
              "About three hundred kilobytes per token"],
    answer: 2, explain: "2 x 80 layers x 8 kv_heads x 128 head_dim x 2 bytes = 327,680 B ~ 330 KB per token, so an 8k session holds ~2.7 GB." },
  { topic: 't2', q: "An 8B model (16 GB bf16 weights, ~1.1 GB KV per 8k session) runs on one 80 GB GPU. Concurrent sessions?",
    options: ["Around sixty concurrent sessions fit comfortably there",
              "Around six concurrent sessions fit comfortably there",
              "Around six hundred concurrent sessions fit there"],
    answer: 0, explain: "80 GB - 16 GB weights = 64 GB free / 1.1 GB per session ~ 58, call it ~60 sessions on a single GPU." },
  { topic: 't2', q: "Standard durability is 3x replication. Roughly what overhead does erasure coding give instead?",
    options: ["Roughly three times the raw data size",
              "Roughly one point five times raw size",
              "Roughly six times the raw data size"],
    answer: 1, explain: "Erasure coding stores ~1.5x raw versus 3x for triple replication -- always say which one you assumed." },
  { topic: 't2', q: "A network link is quoted as 10 Gbps and you treat it as 10 GB/s. What happened?",
    options: ["You overstated the link capacity eight times",
              "You understated the link capacity eight times",
              "No error since the units are equivalent"],
    answer: 0, explain: "Networks quote bits, storage quotes bytes: 10 Gbps = 1.25 GB/s, so calling it 10 GB/s is an 8x overstatement." },
  { topic: 't2', q: "Orders arrive at 25/s while catalog browsing peaks at 15,000 QPS. What does the order path need most?",
    options: ["Aggressive sharding across many database nodes now",
              "A CDN in front of order writes",
              "Durability, idempotency, and audit over raw scale"],
    answer: 2, explain: "25 writes/s fits one well-run relational database for years -- the order path needs qualities (durability, idempotency), not quantities." },
  { topic: 't2', q: "Why voice every assumption as a question, like 'Assume 5x peak -- fair?'",
    options: ["It makes the interviewer do the arithmetic",
              "It lets corrections land before math compounds",
              "It fills silence while you compute quietly"],
    answer: 1, explain: "Every voiced assumption is a correction opportunity -- the interviewer can fix a bad premise before you build five minutes of math on it." },
  { topic: 't2', q: "Sizing for a 5-year horizon with traffic doubling every year multiplies today's estimate by roughly what?",
    options: ["Roughly ten times the current estimated load",
              "Roughly thirty times the current estimated load",
              "Roughly three times the current estimated load"],
    answer: 1, explain: "2^5 = 32 ~ 30x -- a design sized only for today expires in about 18 months." },
  { topic: 't2', q: "Your napkin shows egress near 10 GB/s versus ingest near 100 MB/s. The verdict line is what?",
    options: ["CDN-first, since bandwidth cost dominates the system",
              "Write-first, since ingest is the harder problem",
              "Shard-first, since storage is the binding constraint"],
    answer: 0, explain: "Egress >> ingest (100x here) means bandwidth cost dominates: CDN, compression, and regional replication -- the design must be CDN-first." },
  { topic: 't2', q: "The estimate says petabytes of photo blobs plus small hot metadata rows. Which architecture follows?",
    options: ["One sharded relational database holding photo blobs",
              "A distributed filesystem replacing the metadata database",
              "Object storage behind CDN, metadata in database"],
    answer: 2, explain: "Blobs in PBs cross beyond databases entirely: the classic metadata/blob split puts small hot rows in a DB and immutable blobs in object storage behind a CDN." },
];
