// Phase 1 question bank — t3 · Traffic edge: DNS / CDN / load balancing
// Source lesson: lessons/0003-traffic-edge.html
// First 5 questions reused verbatim from diagnostics/phase1-questions.js.
var PHASE1_BANK_T3 = [
  { topic: 't3', q: "What can an L7 load balancer do that an L4 cannot?",
    options: ["Forward packets using only IPs and ports",
              "Route requests by HTTP path or header",
              "Operate at higher speed with less inspection"],
    answer: 1, explain: "L7 terminates TLS and reads the request, so it can route by path, header, or cookie — paid for with CPU." },
  { topic: 't3', q: "Why are sticky sessions considered a scalability trap?",
    options: ["They make individual servers non-interchangeable under failure",
              "They make every request slower through inspection",
              "They make load balancers forward fewer requests"],
    answer: 0, explain: "State pinned to one box means its death loses sessions and its load can't redistribute. Externalize sessions instead." },
  { topic: 't3', q: "Health checks run every 5 s and mark a backend down after 3 consecutive failures. Worst-case detection time?",
    options: ["About five seconds until traffic stops flowing",
              "About three seconds until traffic stops flowing",
              "About fifteen seconds until traffic stops flowing"],
    answer: 2, explain: "Detection ≈ interval × threshold = 5 s × 3 = 15 s of requests still hitting a dead backend. Tune both knobs." },
  { topic: 't3', q: "Which content belongs on a pull CDN rather than push?",
    options: ["A small set of files updated hourly",
              "A long tail of rarely accessed assets",
              "A single hero video everyone will watch"],
    answer: 1, explain: "Pull fetches on first miss, so you never pay to pre-place assets that may never be requested at that edge." },
  { topic: 't3', q: "Requests vary wildly in cost. Which LB strategy self-corrects best?",
    options: ["Least connections routing toward least busy backends",
              "Round robin rotating evenly across all backends",
              "IP hashing pinning clients to fixed backends"],
    answer: 0, explain: "In-flight count is a live proxy for backend load; slow backends accumulate connections and receive less new work." },

  // ---- 15 new questions ----
  { topic: 't3', q: "Which DNS record maps one name to another name?",
    options: ["An MX record used for mail routing",
              "An A record mapping names to IPv4",
              "A CNAME record aliasing one name onward"],
    answer: 2, explain: "CNAME maps name to name — the alias for www or a CDN hostname — while A maps to IPv4 and MX routes mail." },
  { topic: 't3', q: "Which content fits a push CDN best?",
    options: ["A long tail of rarely requested assets",
              "A small catalog uploaded at release time",
              "Personalized pages that change on every request"],
    answer: 1, explain: "Push means you upload content to edges at release time, which only pays off for small, rarely-changing catalogs." },
  { topic: 't3', q: "How does a reverse proxy relate to a load balancer?",
    options: ["A load balancer is a reverse proxy that balances",
              "A reverse proxy only exists with many backend servers",
              "A load balancer never terminates TLS for backend servers"],
    answer: 0, explain: "A reverse proxy fronts app servers and centralizes TLS, compression, and rate limits; a load balancer is just one that also balances a pool." },
  { topic: 't3', q: "Which DNS record routes email for a domain?",
    options: ["The NS record delegating the domain zone",
              "The A record mapping domain to address",
              "The MX record listing prioritized mail servers"],
    answer: 2, explain: "MX records map a domain to its mail servers with priorities; NS delegates authority and A maps names to IPv4." },
  { topic: 't3', q: "Why do large sites put an L4 tier in front of the L7 tier?",
    options: ["L4 is cheap at line rate, absorbing floods first",
              "L4 can read cookies faster than L7 parsers do",
              "L4 tiers cache static content closer to the users"],
    answer: 0, explain: "L4 forwards packets with minimal work near line rate, so it cheaply absorbs floods and spreads flows across the CPU-heavier L7 tier." },
  { topic: 't3', q: "Your pool mixes big and small machines; requests cost roughly the same. Which algorithm fits?",
    options: ["IP hash, so each client keeps one server",
              "Weighted round robin, sized to each machine's capacity",
              "Least connections, since counts alone determine fair sharing"],
    answer: 1, explain: "With uniform request costs but unequal machines, weighted round robin gives bigger boxes proportionally more — fair by capacity." },
  { topic: 't3', q: "A corporate NAT puts thousands of users behind one IP. What happens under IP-hash routing?",
    options: ["Traffic spreads evenly because users differ by cookie",
              "The NAT blocks hashing so requests fail outright",
              "One unlucky server receives that entire user population"],
    answer: 2, explain: "IP-hash sees one client IP for the whole NAT, so thousands of users hash onto a single hot-spot server." },
  { topic: 't3', q: "Carts live in app-server memory with sticky routing; a redeploy wipes carts mid-purchase. The fix?",
    options: ["Delay every redeploy until all carts empty naturally",
              "Externalize sessions to Redis and go fully stateless",
              "Increase stickiness so clients never switch servers again"],
    answer: 1, explain: "Moving sessions to a shared store makes every server interchangeable, so deploys, autoscaling, and server deaths lose nothing." },
  { topic: 't3', q: "Servers keep bouncing in and out of rotation during GC pauses. What tuning helps?",
    options: ["Require several passing checks before readmission, damping flaps",
              "Shorten the interval so ejections happen even faster",
              "Disable health checking entirely and trust the servers"],
    answer: 0, explain: "Flapping is cured with damping — require multiple passes before readmission and never eject below a minimum pool size." },
  { topic: 't3', q: "Interviewer asks: your load balancer is one box, a single point of failure. Best answer?",
    options: ["DNS re-resolves quickly, so failures fix themselves automatically",
              "Clients retry another datacenter whenever the balancer dies",
              "Run an active-passive pair sharing a floating IP"],
    answer: 2, explain: "The standard answer is an active-passive LB pair exchanging heartbeats; the survivor claims the floating IP via VRRP within seconds." },
  { topic: 't3', q: "Dublin fails and Route 53 flips answers to Oregon, yet some users stay broken. Why?",
    options: ["Oregon rejects any connections that originated inside Europe",
              "Resolvers keep serving cached Dublin answers until expiry",
              "Health checks cannot ever observe a datacenter failure"],
    answer: 1, explain: "DNS answers are cached down to the client for the TTL, so failover only reaches users after their cached record expires." },
  { topic: 't3', q: "An LLM gateway sees 100-token and 10,000-token generations behind identical HTTP calls. Which routing?",
    options: ["Least outstanding requests, reading live queue depth signals",
              "Round robin, because request counts equalize the work",
              "IP hash, because clients should keep their GPU"],
    answer: 0, explain: "With a 100x cost spread, equal counts are not equal work; least-outstanding-requests routes around the server stuck with long generations." },
  { topic: 't3', q: "Origin sees 10,000 RPS; one server handles about 1,000 RPS. With ~30% headroom, how many servers?",
    options: ["Ten servers, since ten thousand divided by one thousand",
              "Twenty servers, because doubling the bare minimum is safest",
              "Thirteen servers, ten for load plus thirty percent headroom"],
    answer: 2, explain: "10,000 / 1,000 = 10 servers at full load; adding ~30% headroom gives 13, exactly the lesson's flash-sale sizing." },
  { topic: 't3', q: "Checks run every 1 s with a failure threshold of 2. Approximate worst-case detection time?",
    options: ["About two seconds before the backend leaves rotation",
              "About one second before the backend leaves rotation",
              "About four seconds before the backend leaves rotation"],
    answer: 0, explain: "Detection ≈ interval × threshold = 1 s × 2 = ~2 s — fast, but one GC pause can now eject a healthy server." },
  { topic: 't3', q: "You change an A record with a 300 s TTL. How long can users keep hitting the old IP?",
    options: ["No time; authoritative servers push updates to resolvers",
              "Up to five minutes, until cached answers expire",
              "At least one day, because resolvers ignore TTLs"],
    answer: 1, explain: "Resolvers cache answers for the TTL, so with 300 s some users hit the old IP for up to five minutes — why DNS is a poor primary failover." },
];
