// Phase 1 question bank — t4 · CAP, consistency & replication
// 20 questions: 5 reused from phase1-questions.js + 15 new.
// Source material: lessons/0004-cap-and-replication.html

var PHASE1_BANK_T4 = [
  // ---- reused from phase1-questions.js (verbatim) ----
  { topic: 't4', q: "During a network partition, what does an AP system do?",
    options: ["Refuses writes until the partition fully heals",
              "Blocks reads while electing a new leader",
              "Serves answers that may be slightly stale"],
    answer: 2, explain: "AP keeps answering during the partition at the price of staleness; CP refuses instead. Operations choose, not whole systems." },
  { topic: 't4', q: "For N = 3 replicas, which (W, R) pair guarantees read-write overlap?",
    options: ["Writes to two and reads from two",
              "Writes to one and reads from two",
              "Writes to two and reads from one"],
    answer: 0, explain: "Overlap requires R + W > N: 2 + 2 = 4 > 3. The other pairs sum to 3, so a read can miss the write set entirely." },
  { topic: 't4', q: "A user posts a comment, refreshes, and it's gone — then reappears. Which guarantee was missing?",
    options: ["Strong consistency enforced across every single replica",
              "Read-your-writes consistency for that user's own session",
              "Monotonic writes ordering across the replica set"],
    answer: 1, explain: "The refresh read a lagging replica. Read-your-writes (e.g. session pinning to leader) fixes exactly this without global strong consistency." },
  { topic: 't4', q: "Two 99.9% services composed in sequence give roughly what availability?",
    options: ["About ninety-nine point eight percent overall availability",
              "About ninety-nine point nine percent overall availability",
              "About ninety-nine point nine nine percent availability"],
    answer: 0, explain: "Serial composition multiplies: 0.999 × 0.999 ≈ 0.998. Every serial dependency eats your availability budget." },
  { topic: 't4', q: "What prevents a paused, stale leader from corrupting storage after failover?",
    options: ["Longer heartbeat intervals set between the two leaders",
              "Retrying failed writes until the old leader recovers",
              "Fencing tokens that reject the stale leader's writes"],
    answer: 2, explain: "Storage checks a monotonically increasing token and rejects writes stamped with an old one — the standard split-brain defense." },

  // ---- new questions ----
  { topic: 't4', q: "In PACELC, what trade-off applies when there is no partition?",
    options: ["Throughput versus durability on every replicated write",
              "Latency versus consistency on every replicated write",
              "Availability versus partition tolerance on every write"],
    answer: 1, explain: "The ELC half: with no partition, waiting for replica confirmation buys consistency at the cost of latency on every write." },
  { topic: 't4', q: "Why is last-write-wins (LWW) dangerous as a multi-leader conflict resolver?",
    options: ["Clock skew means it silently discards real writes",
              "It forces every write through one single leader",
              "It requires atomic clocks in every single datacenter"],
    answer: 0, explain: "With skewed clocks between datacenters 'last' is not really last, so LWW quietly destroys data: fine for caches, unforgivable for orders." },
  { topic: 't4', q: "For N = 5 replicas, which (W, R) pair guarantees read-write overlap?",
    options: ["W = 2 and R = 3",
              "W = 1 and R = 4",
              "W = 3 and R = 3"],
    answer: 2, explain: "Overlap needs R + W > N: 3 + 3 = 6 > 5, while the other pairs sum to exactly 5 and can miss the write set." },
  { topic: 't4', q: "A user refreshes a feed and a comment appears, then refreshes again and it vanishes. Which guarantee is missing?",
    options: ["Read-your-writes consistency scoped to the comment author",
              "Monotonic reads so time never runs backwards",
              "Strong consistency enforced across all replica nodes"],
    answer: 1, explain: "The second read hit a more stale replica; pinning each session to one replica means a user may lag but never time-travels." },
  { topic: 't4', q: "Which replication acknowledgment mode is the common production compromise?",
    options: ["Semi-synchronous with one follower confirming each write",
              "Fully synchronous with every follower confirming writes",
              "Fully asynchronous with zero followers confirming writes"],
    answer: 0, explain: "Semi-sync (e.g. MySQL) waits for at least one follower, avoiding both async's crash data loss and full sync's stalled writes." },
  { topic: 't4', q: "In the LLM gateway project, which consistency does the chat-history store need?",
    options: ["Strong CP consistency across every replica node always",
              "Read-your-writes so users always see their own messages",
              "Weak consistency because stale chat history is harmless"],
    answer: 1, explain: "A user must see the message they just sent, while strangers' replicas may lag; that is exactly read-your-writes." },
  { topic: 't4', q: "What property makes CRDTs suitable for collaborative editors like Figma?",
    options: ["They route every edit through one global leader",
              "They timestamp edits and discard the older one",
              "They mathematically guarantee convergence regardless of delivery order"],
    answer: 2, explain: "CRDTs are data structures whose replicas provably converge no matter what order updates arrive in." },
  { topic: 't4', q: "An interviewer's prompt requires active-active writes in two regions. What must you name immediately?",
    options: ["Your conflict resolution story for concurrent writes",
              "Your total budget for cross-region network bandwidth",
              "Your favorite database vendor for both regions"],
    answer: 0, explain: "The lesson calls proposing multi-leader without a conflict story a red flag, because two leaders can accept conflicting writes to the same key." },
  { topic: 't4', q: "Your failover timeout is set very aggressively low. What risk does the lesson warn about?",
    options: ["Followers will permanently stop replicating from the leader",
              "Leader churn during load spikes when lag peaks",
              "Reads become strongly consistent and therefore too slow"],
    answer: 1, explain: "Failing over too eagerly churns leaders during load spikes, exactly when replication lag, and therefore data loss, is largest." },
  { topic: 't4', q: "Why must the LLM gateway's model-weights registry be strong/CP?",
    options: ["Replicas disagreeing on current weights serve different models",
              "Weights files are too large for eventual replication",
              "Registry reads happen on every single inference request"],
    answer: 0, explain: "Two replicas disagreeing about production weights silently serve different models to different users, the inventory-double-sell of ML platforms." },
  { topic: 't4', q: "Two independent 99.9% providers in parallel with failover give roughly what availability?",
    options: ["About ninety-nine point eight percent overall availability",
              "About ninety-nine point nine percent overall availability",
              "About six nines of overall combined availability"],
    answer: 2, explain: "Failure probabilities multiply in parallel: 1 - (0.001)^2 = 99.9999%, about 32 seconds of downtime a year." },
  { topic: 't4', q: "A 99.99% ('four nines') service allows roughly how much downtime per year?",
    options: ["Roughly eight point eight hours each year",
              "Roughly fifty-three minutes of downtime each year",
              "Roughly five point three minutes each year"],
    answer: 1, explain: "Four nines is about 52.6 minutes a year; three nines allows 8.8 hours and five nines only 5.3 minutes." },
  { topic: 't4', q: "Why do coordination clusters run 3 or 5 nodes, never 2 or 4?",
    options: ["Even counts make consistent hashing rings distribute unevenly",
              "Odd counts guarantee one side can hold majority",
              "Odd counts halve the storage replication cost overall"],
    answer: 1, explain: "Quorum election requires a majority, so with odd sizes the minority side of any partition can never elect a leader." },
  { topic: 't4', q: "After promoting a lagging follower, writes the old leader acknowledged are missing. What failover wound is this?",
    options: ["Lost writes from promoting a behind follower",
              "Split brain between two simultaneously active leaders",
              "Thundering herd of clients retrying failed writes"],
    answer: 0, explain: "GitHub's October 2018 incident is the canonical case: seconds of acknowledged writes existed only on the demoted side." },
  { topic: 't4', q: "Which consistency level fits a video platform's view counter best?",
    options: ["Strong consistency with quorum reads and writes",
              "Read-your-writes consistency pinned to the leader replica",
              "Eventual consistency since approximate counts are fine"],
    answer: 2, explain: "A slightly stale count has no harmful anomaly, so pay nothing for freshness; the dial is set by the worst anomaly's cost." }
];
