// Phase 1 question bank — t5 · RDBMS scaling & indexes
// 20 questions: 5 reused verbatim from diagnostics/phase1-questions.js + 15 new.
// Sourced from lessons/0005-rdbms-scaling.html.

var PHASE1_BANK_T5 = [
  // ---- Reused verbatim from phase1-questions.js ----
  { topic: 't5', q: "Query: last 50 messages for user X ordered by time. Best composite index?",
    options: ["Index on created_at first then user_id second",
              "Index on user_id first then created_at second",
              "Two separate single-column indexes used simultaneously always"],
    answer: 1, explain: "Equality column first, range/order column second: jump to user X, then read a contiguous time-ordered run." },
  { topic: 't5', q: "What is the main cost of adding many indexes to a table?",
    options: ["Every write must also update each index",
              "Every read must scan each index fully",
              "Storage doubles with each new index added"],
    answer: 0, explain: "Indexes are write amplification: each INSERT/UPDATE touches every index B-tree. Reads don't scan unused indexes." },
  { topic: 't5', q: "Federation differs from sharding because federation splits data by…",
    options: ["Hash of the row's primary key value",
              "Ranges of the row's primary key value",
              "Function like users versus products versus forums"],
    answer: 2, explain: "Federation = functional partitioning into separate databases per domain; sharding splits ONE dataset by key." },
  { topic: 't5', q: "Sharding messages by user_id: what breaks when one celebrity gets 100M followers?",
    options: ["One shard becomes hot while others idle",
              "Every shard receives exactly equal write load",
              "Cross shard joins become automatically much faster"],
    answer: 0, explain: "Skewed keys create hot shards — the celebrity problem. Mitigations: key salting, splitting the hot key, dedicated handling." },
  { topic: 't5', q: "When is denormalization the right call?",
    options: ["When write volume dwarfs read volume very heavily",
              "When read performance matters more than write cost",
              "When strict normalization blocks any further schema change"],
    answer: 1, explain: "You duplicate data to kill expensive joins on the read path, paying with heavier, more complex writes." },

  // ---- New: recall ----
  { topic: 't5', q: "In ACID, what does Atomicity guarantee for a multi-statement transaction?",
    options: ["Concurrent transactions never observe each other's work",
              "Committed changes survive any crash that follows",
              "All statements land together or none do"],
    answer: 2, explain: "Atomicity means the whole multi-statement change commits entirely or not at all; the other options describe Isolation and Durability." },
  { topic: 't5', q: "Why can a B-tree serve a range query cheaply?",
    options: ["It descends once then reads leaves sequentially",
              "It caches every leaf page in memory",
              "It hashes each key to one page"],
    answer: 0, explain: "A range query descends to the start of the range once, then walks the sorted leaf pages sequentially." },
  { topic: 't5', q: "Read replicas multiply read capacity. What ceiling do they leave untouched?",
    options: ["The read throughput on the busiest replica",
              "The write throughput of the single primary",
              "The storage capacity of each replica disk"],
    answer: 1, explain: "All writes still flow through the one primary, so replicas do nothing for write volume — the ceiling is still one box." },
  { topic: 't5', q: "You federate into users, catalog, and orders databases. What operation stops existing?",
    options: ["Transactions inside the single orders database",
              "Point reads against the users database",
              "SQL joins spanning users and orders"],
    answer: 2, explain: "Federation kills cross-database joins: 'orders joined to user emails' becomes two queries stitched together in application code." },
  { topic: 't5', q: "What is the classic failure mode of hand-rolled denormalized copies?",
    options: ["Drift when a write path forgets the copy",
              "Deadlocks arising when two reads touch one copy",
              "Slower reads occurring because the copies grow stale"],
    answer: 0, explain: "A copy nobody updates on the write path quietly becomes a lie; every denormalized copy needs a named owner and an update rule." },

  // ---- New: scenario ----
  { topic: 't5', q: "A chat app shards its messages table by conversation_id. What gets painful?",
    options: ["Listing all conversations for one user's sidebar",
              "Rendering the messages inside a single conversation",
              "Appending one new message to a conversation"],
    answer: 0, explain: "Each conversation is one shard, but a user's conversations scatter across shards, so every sidebar load becomes a scatter-gather." },
  { topic: 't5', q: "Query: all orders for customer 42 placed within the last month. Best index?",
    options: ["(created_at, customer_id) with the range column first",
              "(customer_id, created_at) with the equality column first",
              "Separate single-column indexes on customer_id and created_at"],
    answer: 1, explain: "Equality column first, range column last: jump straight to customer 42, then scan a contiguous date-ordered run of leaves." },
  { topic: 't5', q: "An e-commerce site at 10,000 RPS with a 98:2 read/write ratio saturates its one primary. First move?",
    options: ["Shard the orders table across four machines",
              "Federate users, catalog, and orders databases immediately",
              "Add read replicas to absorb the reads"],
    answer: 2, explain: "With 9,800 reads/sec and only 200 writes/sec, replicas are the cheapest and most reversible rung — sharding is the last resort." },
  { topic: 't5', q: "A query reads user_id, created_at, and subject; the index holds only user_id and created_at. What enables index-only scans?",
    options: ["Drop created_at so the index stays small",
              "Add subject into the index definition itself",
              "Add subject to the table's primary key"],
    answer: 1, explain: "Once the index contains every column the query touches, the engine never visits the table — that is a covering index." },
  { topic: 't5', q: "One celebrity key carries a third of the traffic on its shard. Sensible mitigation?",
    options: ["Sub-partition the hot key with a salt",
              "Increase replication factor across all cold shards",
              "Switch every shard to range based partitioning"],
    answer: 0, explain: "Salting splits the whale's rows across shards; isolating whales on dedicated shards or a separate path also works." },
  { topic: 't5', q: "You range-shard an events table by created_at. What happens under write load?",
    options: ["Writes spread evenly across all the shards",
              "Range scans die because adjacent keys scatter",
              "Today's shard absorbs nearly every incoming write"],
    answer: 2, explain: "Range sharding keeps ranges local, but every new row lands in the newest range, so the current shard takes 100% of writes." },
  { topic: 't5', q: "Orders are sharded by customer_id. What happens to the query 'top sellers today'?",
    options: ["It runs entirely on whichever shard holds today",
              "It fans out to every shard and merges",
              "It becomes faster because shards process rows concurrently"],
    answer: 1, explain: "Queries not anchored on the shard key become scatter-gather, and the merged answer is as slow as the slowest shard." },

  // ---- New: numeric / plan-reading ----
  { topic: 't5', q: "An 8 KB page holds roughly 400 branch entries. About how many rows does a depth-3 B-tree reach?",
    options: ["About 64 million rows at that depth",
              "About 160 thousand rows at that depth",
              "About 25 billion rows at that depth"],
    answer: 0, explain: "Depth 3 reaches 400 cubed, roughly 64 million rows; depth 4 reaches about 25 billion — why a point read is O(log n) and usually one SSD touch." },
  { topic: 't5', q: "A table carries five secondary indexes. How many structure writes happen per inserted row?",
    options: ["Five writes since the heap is free",
              "One write because indexes update lazily later",
              "Six writes counting the table plus indexes"],
    answer: 2, explain: "Every insert touches the table plus each index B-tree: one heap write plus five index writes equals six structure writes." },
  { topic: 't5', q: "Naive hash(key) % N sharding, growing from 4 shards to 5. Roughly what fraction of rows move?",
    options: ["About 20 percent since one shard's new",
              "About 80 percent of all rows move",
              "About 50 percent when the hash rebalances"],
    answer: 1, explain: "A key stays put only when hash % 4 equals hash % 5 — true for 4 residues out of 20, so about 80% of rows relocate." }
];
