// Phase 1 question bank — Topic t6: NoSQL Taxonomy & Consistent Hashing
// Source lesson: lessons/0006-nosql-taxonomy.html
// First 5 questions reused verbatim from diagnostics/phase1-questions.js.
var PHASE1_BANK_T6 = [
  // ---- Reused from phase1-questions.js ----
  { topic: 't6', q: "Write-heavy time-series telemetry at massive scale fits which family best?",
    options: ["Wide column stores like Cassandra or Bigtable",
              "Graph databases such as Neo4j or FlockDB",
              "Relational databases with many secondary indexes added"],
    answer: 0, explain: "Wide-column stores are built for huge sequential write volume with key-ordered scans — the telemetry shape." },
  { topic: 't6', q: "With hash(key) % N across 5 nodes, adding a 6th node moves roughly…",
    options: ["Seventeen percent of keys to new locations",
              "Zero percent of keys to new locations",
              "Eighty percent of keys to new locations"],
    answer: 2, explain: "Mod-N remaps almost everything (~5/6 ≈ 83%); a consistent-hash ring moves only ~1/6 ≈ 17%. That asymmetry is the whole point." },
  { topic: 't6', q: "What problem do virtual nodes solve in consistent hashing?",
    options: ["They stop hot keys from overloading nodes",
              "They smooth uneven key distribution across nodes",
              "They remove the need for any rebalancing"],
    answer: 1, explain: "Few physical nodes land unevenly on the ring; hundreds of vnodes per node average out the arc lengths." },
  { topic: 't6', q: "Consistent hashing balances key count but NOT…",
    options: ["Load when key popularity is heavily skewed",
              "Membership when nodes join the ring frequently",
              "Placement when keys hash to equal values"],
    answer: 0, explain: "A zipf-hot key still lands on one node. Count balance ≠ load balance; hot keys need replication or caching on top." },
  { topic: 't6', q: "BASE stands for basically available, soft state, and…",
    options: ["Strict serializability across every replica set",
              "Synchronous replication across every data center",
              "Eventual consistency reached after writes stop"],
    answer: 2, explain: "BASE is the deliberate opposite of ACID: keep answering, tolerate transient disagreement, converge eventually." },

  // ---- New: recall ----
  { topic: 't6', q: "In BASE, what does 'basically available' actually promise?",
    options: ["The system keeps answering during partial failures",
              "The system rejects writes during network partitions",
              "The system guarantees fresh reads on replicas"],
    answer: 0, explain: "Basically Available means the store keeps responding even while parts of it are failing; freshness is traded away, not availability." },
  { topic: 't6', q: "Which system does the lesson name as the canonical key-value store?",
    options: ["MongoDB, which stores queryable JSON documents",
              "Redis, which serves sub-millisecond key lookups",
              "Neo4j, which stores nodes and edges"],
    answer: 1, explain: "Redis is the canonical KV store: get/put by key with nothing between you and the hash table, hence sub-millisecond latency." },
  { topic: 't6', q: "In a wide-column store, what does the partition key do?",
    options: ["Sorts rows within a single partition",
              "Indexes every column for value queries",
              "Routes each row to its node"],
    answer: 2, explain: "The partition key routes a row to a node; the clustering key then sorts rows within that partition." },
  { topic: 't6', q: "Per the lesson, which pressure genuinely justifies leaving SQL?",
    options: ["Read traffic that replicas could still absorb",
              "Write volume that must shard across nodes",
              "Team preference for more fashionable NoSQL tooling"],
    answer: 1, explain: "Read scale is solved by replicas and caches; it is write scale that forces sharding and a move off one SQL box." },
  { topic: 't6', q: "Why do graph databases win at deep relationship traversals?",
    options: ["Cost scales with the subgraph actually touched",
              "Cost scales with total rows scanned everywhere",
              "Cost stays constant regardless of query depth"],
    answer: 0, explain: "Edges are stored as direct pointers, so a depth-3 walk costs proportional to the subgraph visited, not N SQL self-joins." },

  // ---- New: scenario ----
  { topic: 't6', q: "Every page view triggers an auth lookup of a 200-byte session blob at 20k reads/sec. Best home?",
    options: ["Postgres, with secondary indexes on sessions",
              "Cassandra, partitioned by session creation time",
              "Redis, doing pure key-value point lookups"],
    answer: 2, explain: "Sessions are pure key lookups with zero joins and a sub-ms budget — the textbook Redis key-value workload." },
  { topic: 't6', q: "You must flag accounts sharing a device or card with known fraudsters within 3 hops. Which store?",
    options: ["A graph database storing edges as pointers",
              "A document store holding one account each",
              "A wide-column store keyed by account id"],
    answer: 0, explain: "Multi-hop fraud-ring queries are edge walks in Neo4j and a self-join catastrophe everywhere else." },
  { topic: 't6', q: "A shopping cart must accept updates even during partial failure; brief staleness is tolerable. Which contract fits?",
    options: ["ACID transactions with synchronous replication everywhere",
              "BASE semantics on a Dynamo-style store",
              "Strict serializability across all replicas always"],
    answer: 1, explain: "Amazon's cart runs on Dynamo because an unavailable cart loses the sale now, while a briefly stale cart merely annoys." },
  { topic: 't6', q: "A 10M-product catalog where each category carries different, weekly-changing attributes. Best family?",
    options: ["Document store, one product per document",
              "Relational schema, migrating on each change",
              "Graph database, linking products to attributes"],
    answer: 0, explain: "Schema velocity is the named pressure: documents let each product carry its own attributes with no migrations." },
  { topic: 't6', q: "Orders and payments at 23 writes/sec need order, inventory, and payment updated atomically. Move where?",
    options: ["Cassandra, for its append-friendly LSM writes",
              "Redis, for its sub-millisecond write path",
              "Nowhere; Postgres already handles this fine"],
    answer: 2, explain: "There is no scale pressure at 23 writes/sec and the workload demands multi-row ACID, so staying in Postgres is the answer." },
  { topic: 't6', q: "An LLM gateway checks rate-limit counters and API keys on every request with a sub-ms budget. Family?",
    options: ["Wide-column, like Cassandra, for time series",
              "Graph, like Neo4j, for traversal queries",
              "Key-value, like Redis, for point lookups"],
    answer: 2, explain: "Per-request counter and key lookups with a sub-ms budget are the key-value killer use case from the project step." },
  { topic: 't6', q: "A node crashes out of a consistent-hash ring. What happens to key placement?",
    options: ["Every key rehashes to a new owner",
              "Only its arc moves to its successor",
              "All keys move counter-clockwise one node over"],
    answer: 1, explain: "Only the dead node's arc shifts to its clockwise successor (~1/N of keys); the other keys never notice." },

  // ---- New: numeric ----
  { topic: 't6', q: "A consistent-hash ring grows from 5 to 6 nodes. Roughly what fraction of keys move, and where?",
    options: ["About 17 percent, all onto the newcomer",
              "About 83 percent, scattered across every node",
              "About 50 percent, split between two nodes"],
    answer: 0, explain: "A new node takes over only the arc back to its counter-clockwise neighbor, ~1/(N+1) of keys, every one moving to it." },
  { topic: 't6', q: "The lab measures a 3.2x overload with 1 vnode per node. At 100 vnodes, the worst node carries roughly…",
    options: ["About 2.5 times its fair share",
              "About 1.08 times its fair share",
              "About 0.5 times its fair share"],
    answer: 1, explain: "Hundreds of small scattered arcs let the law of large numbers average each node toward 1/N, dropping 3.2x to about 1.08x." },
  { topic: 't6', q: "Under hash(key) % N, shrinking from 5 nodes to 4 moves roughly what share of keys?",
    options: ["Roughly 20 percent of the keys",
              "Roughly 80 percent of the keys",
              "Roughly 4 percent of the keys"],
    answer: 1, explain: "Mod-N is catastrophic in both directions: going 5 to 4 remaps ~80% of keys, nearly as bad as the ~83% when adding one." },
];
