// Phase 1 question bank — t8 · Queues, backpressure & protocols
// Source lesson: lessons/0008-async-and-communication.html
// First 5 questions reused verbatim from diagnostics/phase1-questions.js.

var PHASE1_BANK_T8 = [
  // ---- Reused from phase1-questions.js (verbatim) ----
  { topic: 't8', q: "Why cap a queue's length and reject with 503 instead of queueing everything?",
    options: ["Unbounded queues drop messages once memory fills",
              "Rejections cost less than any queueing does",
              "Unbounded queues hide latency that grows unbounded"],
    answer: 2, explain: "Past saturation the queue only manufactures wait time; fast rejection keeps served requests fast and pushes overload to clients." },
  { topic: 't8', q: "At-least-once delivery plus what makes reprocessing safe?",
    options: ["Idempotency keys deduplicating repeated message handling",
              "Exactly once semantics from the broker",
              "Ordering guarantees within every consumer group"],
    answer: 0, explain: "Duplicates are inevitable at-least-once; idempotent handlers make the duplicate a no-op. That pair is the industry standard." },
  { topic: 't8', q: "Why add jitter to exponential backoff?",
    options: ["It shortens the average retry waiting time",
              "It desynchronizes clients retrying at identical moments",
              "It guarantees every retry eventually will succeed"],
    answer: 1, explain: "Without jitter, all failed clients retry in the same instant — a synchronized thundering herd that re-kills the service." },
  { topic: 't8', q: "Little's law: 200 RPS arrival and 0.5 s average latency means how many in-flight requests?",
    options: ["One hundred requests in flight on average",
              "Four hundred requests in flight on average",
              "Fifty requests in flight on average overall"],
    answer: 0, explain: "L = λW = 200 × 0.5 = 100. Queue depth is latency made visible — the leading indicator to alert on." },
  { topic: 't8', q: "When is UDP the right choice over TCP?",
    options: ["When every byte must arrive in order",
              "When connections are expensive to establish repeatedly",
              "When late data is worse than lost"],
    answer: 2, explain: "Voice, video, game state: a retransmitted stale packet is useless. TCP's guarantees actively hurt there." },

  // ---- New: recall ----
  { topic: 't8', q: "What distinguishes a task queue like Celery from a message queue like Kafka?",
    options: ["It manages background job execution atop brokers",
              "It moves raw data buffers between services",
              "It guarantees exactly-once delivery for every job"],
    answer: 0, explain: "A message queue moves and buffers data between services; a task queue sits one level up, managing worker pools, retry policy, and results for background jobs." },
  { topic: 't8', q: "Which workloads can reasonably accept at-most-once delivery semantics?",
    options: ["Payment charges where every message must apply",
              "Metrics, logs, and presence pings tolerating loss",
              "Order confirmations that customers are actively awaiting"],
    answer: 1, explain: "At-most-once loses messages silently, which is acceptable only where loss is tolerable — metrics, logs, and presence pings, never payments or confirmations." },
  { topic: 't8', q: "Why can new Kafka consumers replay history that RabbitMQ consumers cannot?",
    options: ["Kafka brokers route messages using smart exchanges",
              "Kafka deletes each message on consumer acknowledgment",
              "Kafka retains messages in an append-only log"],
    answer: 2, explain: "Kafka retains messages in the partitioned log for days instead of deleting on ack, so a new consumer simply starts reading from an earlier offset." },
  { topic: 't8', q: "Why is gRPC the standard default for internal service-to-service traffic?",
    options: ["It offers human-readable text payloads debuggable via curl",
              "It provides typed contracts, compact binary payloads, streaming",
              "It guarantees loose coupling so clients evolve freely"],
    answer: 1, explain: "Inside the datacenter you own both ends, so take gRPC's enforced .proto schema, compact binary encoding, and first-class streaming; REST stays at the public edge." },
  { topic: 't8', q: "Which HTTP verbs does the spec define as idempotent?",
    options: ["GET, PUT, and DELETE are defined idempotent",
              "POST, PUT, and PATCH are defined idempotent",
              "Only GET requests are ever considered idempotent"],
    answer: 0, explain: "GET, PUT, and DELETE are idempotent by definition while POST is not, which is exactly why payment APIs layer idempotency keys onto POST." },

  // ---- New: scenario ----
  { topic: 't8', q: "A service blips for 2 seconds, recovers, then immediately falls over again, and the cycle repeats. What is the likely mechanism?",
    options: ["The load balancer keeps routing toward dead instances",
              "Rejected clients retry simultaneously as a thundering herd",
              "The garbage collector pauses every recovering instance repeatedly"],
    answer: 1, explain: "Clients rejected at the same moment retry at the same moment, hitting the recovering service with a synchronized wave that re-kills it; exponential backoff with full jitter breaks the cycle." },
  { topic: 't8', q: "A vendor claims their Kafka pipeline gives exactly-once delivery to your payment API. What is the correct audit finding?",
    options: ["The claim holds because Kafka transactions are end-to-end",
              "The claim holds if consumers commit offsets synchronously",
              "The claim breaks once side effects leave Kafka"],
    answer: 2, explain: "Kafka transactions provide exactly-once only within Kafka's own boundary; the moment the consumer touches an external payment API you are back to at-least-once plus idempotency keys." },
  { topic: 't8', q: "An interactive checkout API and a nightly report generator share a worker pool that saturates. Which design is right?",
    options: ["Bound the queue; shed report jobs before checkouts",
              "Queue all work unboundedly since reports eventually complete",
              "Block checkout callers until report jobs finish draining"],
    answer: 0, explain: "Batch work has hours of deadline slack while a browsing user has about a second of patience, so interactive traffic is admitted first and reports are shed first." },
  { topic: 't8', q: "You are designing a multiplayer game streaming rapid position updates where stale positions are worthless. Which transport fits?",
    options: ["TCP, because ordered reliable delivery prevents position glitches",
              "UDP, because late updates are worse than lost",
              "gRPC streaming, because typed contracts prevent malformed updates"],
    answer: 1, explain: "A retransmitted stale position is garbage by the time it arrives; skip it and render the next one, which is exactly the case where UDP beats TCP." },
  { topic: 't8', q: "Instead of rejecting when saturated, your service blocks callers until capacity frees up. Why is this dangerous?",
    options: ["The queue relocates into callers' thread pools, cascading",
              "Blocked connections consume bandwidth that healthy requests need",
              "Blocking violates HTTP semantics for every long request"],
    answer: 0, explain: "Blocking does not remove the queue — it relocates it into the callers' threads, filling their pools and climbing the call graph one tier at a time, a cascading failure in slow motion." },
  { topic: 't8', q: "During an outage your servers show 100% utilization yet users receive nothing. What is the signature diagnosis?",
    options: ["The database is deadlocked, so responses never commit",
              "The network is partitioned, so responses never arrive",
              "Servers complete requests whose callers already timed out"],
    answer: 2, explain: "This is zombie work from queue collapse — waits exceeded every client timeout, so capacity burns on answers nobody is waiting for: full utilization, zero goodput." },
  { topic: 't8', q: "Mobile app, API gateway, and backend client each retry 3 times. Per Google SRE guidance, what is the fix?",
    options: ["Increase every layer's retry count for more resilience",
              "Retry at one layer only, with capped budget",
              "Disable all retries everywhere and fail requests immediately"],
    answer: 1, explain: "Layered retries multiply — 3 x 3 x 3 turns one tap into 27 requests — so retry at a single layer, cap attempts around 3, and enforce a retry budget near 10% extra load." },

  // ---- New: numeric ----
  { topic: 't8', q: "Your SLO allows 2 seconds of queueing and workers drain 300 jobs per second. What queue bound does Little's law give?",
    options: ["Six hundred jobs is the correct bound",
              "One hundred fifty jobs is the bound",
              "Three thousand jobs is the correct bound"],
    answer: 0, explain: "L = lambda x W = 300 x 2 = 600; anything deeper stores requests you have already decided to serve too late, so reject them instead." },
  { topic: 't8', q: "An M/M/1 service at 90% utilization is pushed to 95%. Roughly what happens to mean queueing delay?",
    options: ["It rises about five percent, matching utilization",
              "It roughly doubles, from 9x to 19x",
              "It stays flat until utilization reaches 100%"],
    answer: 1, explain: "Delay scales like rho/(1-rho) times service time, so 90% gives 9x and 95% gives 19x — the hockey stick that makes 'we are at 95% and fine' a lit fuse." },
  { topic: 't8', q: "A user's tap passes through three layers that each retry 3 times on failure. Worst case, how many requests hit the bottom service?",
    options: ["Nine requests reach the bottom service overall",
              "Three requests reach the bottom service overall",
              "Twenty-seven requests reach the bottom service overall"],
    answer: 2, explain: "Retries multiply through layers: 3 x 3 x 3 = 27 requests from one user tap, arriving precisely when the bottom service is least able to serve them." }
];
