// Phase 1 quiz bank — t9 · Interview execution framework
// Source lesson: lessons/0009-interview-os.html
// First 5 questions reused verbatim from diagnostics/phase1-questions.js.

var PHASE1_BANK_T9 = [
  // ---- reused verbatim from phase1-questions.js ----
  { topic: 't9', q: "What is the correct FIRST move after receiving a design prompt?",
    options: ["Sketch the architecture you envision quickly",
              "Clarify users, scale, SLOs, and scope",
              "List every technology you plan using"],
    answer: 1, explain: "Requirements before boxes. Designing before scoping is the most-cited failure pattern in interviewer debriefs." },
  { topic: 't9', q: "Estimation numbers earn credit in an interview only when they…",
    options: ["Drive later decisions like replica counts",
              "Match the interviewer's own private calculations",
              "Reach three significant figures of precision"],
    answer: 0, explain: "'We computed 50k QPS, so one box won't do' — unused numbers are theater; used numbers are engineering." },
  { topic: 't9', q: "Which behavior is a reported interview anti-pattern?",
    options: ["Checking whether to deepen or move on",
              "Naming bottlenecks before the interviewer ever asks",
              "Thinking silently for long stretches of time"],
    answer: 2, explain: "The interview grades your reasoning stream. Silence hides it; narrating trade-offs aloud is the graded skill." },
  { topic: 't9', q: "Roughly how should a 50-minute design round be sequenced?",
    options: ["Clarify then estimate then design then deepen",
              "Design then clarify then estimate then deepen",
              "Estimate then design then clarify then deepen"],
    answer: 0, explain: "Clarify (~5–8) → estimate (~5) → high-level (~15) → deep-dive and scale (~20). Each step feeds the next." },
  { topic: 't9', q: "The strongest way to present a technical choice is…",
    options: ["Naming technologies used by top companies",
              "Two options, one chosen, with because",
              "Deferring the decision until implementation time"],
    answer: 1, explain: "'I see A and B; picking B because X' shows judgment. Name-dropping and deferral both dodge the actual decision." },

  // ---- new questions ----
  { topic: 't9', q: "Which step of the 50-minute round receives the largest time budget, and why?",
    options: ["Clarify, because requirements decide every downstream choice",
              "High-level design, because diagrams demonstrate the breadth",
              "Deep dive, because depth carries senior signal"],
    answer: 2, explain: "Deep dive plus scale gets roughly 20 of the 50 minutes because dissecting 1-2 components under load is where offers are won." },
  { topic: 't9', q: "In the lesson's checkout example, which of these is a NON-functional requirement?",
    options: ["p99 under 500 ms at peak",
              "Charge the card exactly one time",
              "Email a receipt after each order"],
    answer: 0, explain: "Functional requirements say what the system does; non-functional ones like p99 latency say how well it must do it." },
  { topic: 't9', q: "According to the lesson's anti-pattern table, which move fails candidates?",
    options: ["Following an interviewer hint the moment it lands",
              "Drawing ten shallow boxes with zero depth anywhere",
              "Stating what is out of scope in writing"],
    answer: 1, explain: "Breadth with zero depth is a listed anti-pattern; two components dissected under load beat ten components merely named." },
  { topic: 't9', q: "Which trio names the lesson's three rehearsable communication moves?",
    options: ["Apologizing, hedging, and deferring decisions",
              "Estimating, sharding, and caching aggressively",
              "Signposting, checking in, thinking aloud"],
    answer: 2, explain: "Signposting, checking in, and thinking aloud are the three verbal tools that make your reasoning visible and gradable." },
  { topic: 't9', q: "Which four question families does Step 1 (Clarify) use to buy the right problem?",
    options: ["Users, scale, read/write ratio, SLOs",
              "Languages, frameworks, cloud vendors, databases",
              "Salary, team size, tooling, deadlines"],
    answer: 0, explain: "Users and use cases, scale, read/write ratio, and SLOs are the four families that turn an underspecified prompt into a contract." },
  { topic: 't9', q: "Mid-drawing, the interviewer murmurs 'what about that cache going cold?' You should...",
    options: ["Finish your agenda, then revisit later",
              "Address the cold-cache case right now",
              "Note it under the more-time list"],
    answer: 1, explain: "Hints are the rubric leaking through; following one immediately is free information about a dimension being scored." },
  { topic: 't9', q: "At minute 30 you are still drawing high-level boxes. What is the best move?",
    options: ["Keep drawing until every box feels fully complete",
              "Restart the interview with a much smaller scope",
              "Say you are over budget and move on"],
    answer: 2, explain: "Budgets are guardrails, not laws; the skill is noticing overrun and saying so aloud: 'parking this, moving to the data model.'" },
  { topic: 't9', q: "You see two equally hard components for the deep dive. What is the strongest move?",
    options: ["Name both, then offer the interviewer the choice",
              "Cover both shallowly so neither one gets missed",
              "Wait silently until the interviewer picks one themselves"],
    answer: 0, explain: "Offering the choice wins either way: you have already shown you know where both dragons live." },
  { topic: 't9', q: "You need thirty seconds to weigh push versus pull for feed delivery. What do you do?",
    options: ["Think silently so interruptions cannot derail your reasoning",
              "Say aloud: 'I am weighing push versus pull'",
              "Ask the interviewer to please decide for you"],
    answer: 1, explain: "The interviewer can only grade what they can hear; thirty seconds of dead air grades as lost." },
  { topic: 't9', q: "A candidate opens with 'I would use Kafka and Cassandra here.' What went wrong?",
    options: ["Technologies should be conclusions, not opening moves",
              "Kafka and Cassandra are simply outdated choices",
              "The candidate should have named more tools"],
    answer: 0, explain: "Naming tech before any requirement exists signals pattern-matching, not engineering; the tech may not fit the problem you have not scoped." },
  { topic: 't9', q: "Prompt: 'design a news feed.' Which deep-dive component carries the most senior signal?",
    options: ["The login form and password hashing",
              "The CDN serving static profile images",
              "Fan-out delivery when celebrity accounts post"],
    answer: 2, explain: "Celebrity fan-out is where the write-amplification dragon lives; Twitter's hybrid fan-out design exists precisely because of it." },
  { topic: 't9', q: "Which sentence states the order-to-email queue trade-off the way the lesson teaches?",
    options: ["A queue is industry standard, so every serious checkout obviously needs one",
              "Slow mail cannot block checkout; the cost is a slightly later receipt",
              "Queues add complexity, so we should just avoid mentioning any downsides here"],
    answer: 1, explain: "A narrated trade-off names the benefit and the accepted cost, then ties the cost back to what the SLOs tolerate." },
  { topic: 't9', q: "Per the lesson, what does Anthropic's design round explicitly watch for?",
    options: ["Whether the candidate structures the ambiguity themselves",
              "Whether the candidate has memorized many architectures",
              "Whether the candidate waits politely for guidance"],
    answer: 0, explain: "The round is calibrated for engineers who drive from requirements to estimates to design without needing prompting." },
  { topic: 't9', q: "At minute 40 the interviewer asks 'but what about fraud?' You scoped fraud out at minute 3. Best response?",
    options: ["Apologize for the oversight and redesign around fraud",
              "Pretend fraud handling was in the design already",
              "Cite the written exclusion, offer pulling it in"],
    answer: 2, explain: "Written exclusions exist for exactly this moment: 'scoped out at minute 3, happy to pull it back in.'" },
  { topic: 't9', q: "With three minutes left and topics still uncovered, how do you close the hour?",
    options: ["Rush through every remaining component at maximum speed",
              "Name the paging metric, then list more-time items",
              "Stop talking and let the interviewer wrap up"],
    answer: 1, explain: "Monitoring plus the more-time list converts everything you did not cover from an omission into a roadmap, ending the hour as the driver." },
];
